C(.devops) account-admin:~/environment/Udacity-Project-4 (main) $ ./run_kubernetes.sh 
Error from server (AlreadyExists): pods "udacity-project-4" already exists
NAME                READY   STATUS    RESTARTS   AGE
udacity-project-4   1/1     Running   0          6m47s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000
Handling connection for 8000
^C * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 203-854-522
[2021-11-30 17:36:06,568] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}